spring:
  cloud:
    gateway:
      routes:
        - id: home
          uri: http://localhost:8080
          predicates:
            - Path=/
        - id: patient
          uri: http://localhost:9000
          predicates:
            - Path=/patient
        - id: note
          uri: http://localhost:9003
          predicates:
            - Path=/note
        - id: assessment
          uri: http://localhost:9004
          predicates:
            - Path=/assessment
management:
  endpoints:
    web:
      exposure:
        include: "*"