spring:
  cloud:
    gateway:
      routes:
        - id: home
          uri: http://localhost:8080
          predicates:
            - Path=/
        - id: patient
          uri: http://localhost:8080
          predicates:
            - Path=/patient
        - id: note
          uri: http://localhost:8080
          predicates:
            - Path=/note
management:
  endpoints:
    web:
      exposure:
        include: "*"